### ISSUE TITLE
Additional text

### ISSUE THREAD

**Issue by sjones-hep-ph-liv-ac-uk** [gridpp/user-guides#2]
Sorry to be picky, Tom, but I'm trying out this GitHub system. Please make following change to DIRAC-getting-started.md.

Change:

> Joining the Imperial DIRAC mailing list: once you have subscribed, 
> you should be able to view the subscribers list from the list homepage 
> and see that you're on it.

To:

> Joining the Imperial DIRAC mailing list: once you have subscribed AND
> BEEN APPROVED 
> you should be able to view the subscribers list from the list homepage 
> and see that you're on it.

**Comment by twhyntie** [comment]
Hi @sjones-hep-ph-liv-ac-uk,

Good spot, thanks. Would:

> ...once you have  _**subscribed**_ and _**been approved**_ you should...

be OK? I'm not a fan of uppercase, it's seems a bit shouty :-)

Cheers, Tom

**Comment by twhyntie** [comment]
Fixed by #4
