### ISSUE TITLE
Functionally disconnected

### ISSUE THREAD

**Issue by sjones-hep-ph-liv-ac-uk** [gridpp/user-guides#5]
In this section: DIRAC client installation
Consider these two lines:
-    I have installed a DIRAC client on my local system (following the instructions here);
-    I have generated a proxy with my grid certificate (following the instructions here).

The first instruction links to a page that tells me 1) how to install AND 2) how to make a proxy (see last line of `<pre>` section.) The second instruction links to a subsection that is no longer present (called 'Create_a_proxy_for_a_community'). These ideas are almost OK but they need a bit of reworking to make it all connect up properly.

**Comment by twhyntie** [comment]
@sjones-hep-ph-liv-ac-uk I think it having those steps listed separately is a good thing. I'd rather change the [wiki page](https://www.gridpp.ac.uk/wiki/Quick_Guide_to_Dirac) as generating a proxy is lumped in with installation. I'll take a look.
