### ISSUE TITLE
$DIRACDIR not defined

### ISSUE THREAD

**Issue by sjones-hep-ph-liv-ac-uk** [gridpp/user-guides#6]
Line: Upon sourcing . $DIRACDIR/bashrc

If people take $DIRACDIR literally, the process won't work. Suggest to say

Upon sourcing bashrc in the installation directory (e.g. cd ~/dirac_ui/; . bashrc), ...

Or some other form of words to convey the same idea.

**Comment by twhyntie** [comment]
Fixed by #23.
