### ISSUE TITLE
More  'ordering' issues

### ISSUE THREAD

**Issue by sjones-hep-ph-liv-ac-uk** [gridpp/user-guides#7]
You have no control over this, but it's still an issue. In "Tutorial 4 Job management basics", reference is made to "dirac-dms-add-file", yet data management is not discussed until "Tutorial 5 Data management basics". Thus user cannot get get list of supported SEs and thus user cannot complete Tutorial 4 unless he has already done Tutorial 5. Good luck sorting out this one; you'll need it!

**Comment by twhyntie** [comment]
@sjones-hep-ph-liv-ac-uk True. To be honest the official tutorials will need to be replaced anyway as there are Imperial-specific factors to consider, so we can factor this in when re-writing these.

Thanks again, Tom
