### ISSUE TITLE
Missing information in instructions to configure Ganga

### ISSUE THREAD

**Issue by willfurnell** [gridpp/user-guides#71]
I've just run through the instructions on configuring Ganga to use the DIRAC backend but it seems they are incomplete as I got the following error when using them (from Ganaga on launch):
```
ERROR    problems with loading Plugin /cvmfs/ganga.cern.ch/Ganga/install/LATEST/python/GangaDirac
ERROR    Reason: GangaValueError:  ('DIRAC Proxy `group` is not set. Set this in ~/.gangarc in `[defaults_DiracProxy]/group`',)
```

To rectify this, I added another configuration option in the ~/.gangarc file:
```
[defaults_DiracProxy]
group = cernatschool.org_user
```
This seemed to fix the issue, although now when launching Ganga I also get the following errors:
```
ERROR    unknown configuration section: [defaults_GridCommand]
ERROR    unknown options [LCG]GLITE_ENABLE
```
This time it does launch into the command prompt though.

Thanks,
Will.

**Comment by twhyntie** [comment]
Thanks Will - I think there's been a new release of Ganga since the last UserGuide update and the configuration file options in `.gangarc` have changed. Will take a look now.

**Comment by twhyntie** [comment]
PS: while I'm here - how do I get an account on TAPAS? Are you on the [slack group](https://researchinsch.slack.com)?

**Comment by willfurnell** [comment]
I am on the slack group, under the username 'will'. You can register an account here: http://starserver.thelangton.org.uk/tapas/accounts/register/

**Comment by twhyntie** [comment]
Great, thanks! 😄

**Comment by twhyntie** [comment]
OK, so I've tested and it looks like 6.3.0 doesn't set a default value. I've raised an issue on the Ganga GitHub repo [here](https://github.com/ganga-devs/ganga/issues/895) - this isn't a UserGuide issue.

The LCG option _is_ defunct now so I'll remove that from the UserGuide... for me, Ganga removes it from `.gangrc` automatically, but of course we shouldn't be adding it in the first place :smile:

**Comment by willfurnell** [comment]
Sounds great, thank you!

**Comment by twhyntie** [comment]
They're on it :smile:: https://github.com/ganga-devs/ganga/pull/896
