### ISSUE TITLE
Ganga needs defaultSE to be set (Writing data to the Grid)

### ISSUE THREAD

**Issue by willfurnell** [gridpp/user-guides#74]
In relation to the issue https://github.com/ganga-devs/ganga/issues/906 it looks like the UserGuide needs to include instructions for setting
```
[defaults_DiracFile]
defaultSE = 'UKI-LT2-QMUL2-disk'
```
in the users ~/.gangarc for when they use DiracFile for data output in the 'Writing data to the Grid' section.
I'm happy to submit the changes for this if nessasary.
Thanks,
Will.

**Comment by twhyntie** [comment]
@willfurnell Thanks - but there are a few other things to update with the other issues so I'll do it all in one go 😄 
Thanks again for spotting the problem and finding the fix - much appreciated!
